# 网站基本信息
title: "吴睿林的个人网站"
email: 2321495449@qq.com
description: "If you find it, you find it"
baseurl: ""
url: "https://rl-wu.github.io"
github_username: rl-wu

# Jekyll配置
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 栏目设置
categories:
  - name: "课程学习"
    slug: "course"
  - name: "科研"
    slug: "research" 
  - name: "心得"
    slug: "thoughts"
  - name: "杂谈"
    slug: "misc"

# 网站设置
timezone: Asia/Shanghai
encoding: utf-8

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md